### ISSUE TITLE
Cannot find module 'ctags' 

### ISSUE THREAD

**Issue by Filirom1** [mozilla/doctorjs#18]
Hi, 

I have some difficulties installing doctorjs (jsctags).

```
$ git clone https://github.com/mozilla/doctorjs.git
$ cd doctorjs/
$ git submodule update --init --recursive
$ sudo make install
$ jsctags ~/jsProject/lib/
```

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'ctags'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at Object.<anonymous> (/usr/local/bin/jsctags:45:13)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)

```
$ node --version
v0.4.11

$ uname -a
Linux romain 3.0-ARCH #1 SMP PREEMPT Tue Aug 30 07:32:23 UTC 2011 i686 Intel(R) Atom(TM) CPU N270 @ 1.60GHz GenuineIntel GNU/Linux
```

Help is welcomed.

Cheers
Romain

**Comment by khanakia** [comment]
Hi
There can 2 reason that you are getting above error
1. ctags module is not installed
2. if ctags module installed correctly then NODE_PATH is not set which is causing error.
So i have Centos server and my shared node_modules are installed in that directory /usr/local/lib/node_modules

So i did SSH in my system as normal user (Not root user) and then did fire the following command
export NODE_PATH=/usr/local/lib/node_modules

After that problem SOLVED

**Comment by mrkhanakia** [comment]
Hi
There can 2 reason that you are getting above error
1. ctags module is not installed
2. if ctags module installed correctly then NODE_PATH is not set which is causing error.
So i have Centos server and my shared node_modules are installed in that directory /usr/local/lib/node_modules

So i did SSH in my system as normal user (Not root user) and then did fire the following command
export NODE_PATH=/usr/local/lib/node_modules

After that problem SOLVED
